config/routes.rb
Rails.application.routes.draw do

  resources :cities
  
  root 'cities#index'
  get 'auth/:provider/callback', to: "sessions#create_face"
  delete 'sign_out', to: "sessions#destroy_face", as: 'sign_out'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'index' => 'cities#index'
  get 'find' => 'cities#show_cities'
  get 'cities/show'
  get 'show' => 'cities#show'
  get 'compare' => 'cities#compare'
	get 'ranking' => 'cities#ranking'
  post 'compare' => 'cities#compare'
  post 'find' => 'cities#show_cities'
  get 'about' => 'static_pages#about'
  get 'contact' => 'contacts#new', via: 'get'
  get 'references' => 'static_pages#references'
  get "static_pages/download_pdf"
  get "/articles", to: "articles#generate_report", as: :articles
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'edit' => 'users#edit'
  post 'edit' => 'users#update'
  resources :users

  resources :cities do
    resources :comments
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/user.rb
class User < ActiveRecord::Base

	before_save {self.email = self.email.downcase} #self significa o usuario atual (current_user)
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:true, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, :on => :create
  has_one :profile_quiz
  #serialize :answer_quiz, Array

  def self.from_omniauth(auth_hash)
    user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
    user.name = auth_hash['info']['name']
    user.email = auth_hash['info']['email']
    user.password = '123456'
    user.password_confirmation = '123456'
    User.all.each do |f|
      if f.email == user.email
        return user
      end
    end
    user.save!
    user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @profile_quiz = ProfileQuiz.new
    if @user.profileQuiz_id == nil 
      if params[:uber] && params[:demographic_density] && params[:area] && params[:population]
            @profile_quiz.uber = params[:uber].to_i
            @profile_quiz.demographic_density = params[:demographic_density].to_i
            @profile_quiz.area = params[:area].to_i
            @profile_quiz.population = params[:population].to_i
            @profile_quiz.users_id = params[:id].to_i    
            @profile_quiz.save!
      else
        flash[:error] = "Precisa responder todos os campos!"
        render 'show'
        flash[:error] = nil
      end
      @user.profileQuiz_id = @profile_quiz.id
      @user.save!
    else
      #do nothing
    end

    @user = User.find(params[:id])	
 end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Registrado com sucesso"
      render 'sessions/new'
      flash[:notice] = nil
      #log_in @user
  		#redirect_to @user
    else
      flash[:error] = "Cadastro inválido"
      render 'new'
      flash[:error] = nil
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_url
  end


  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :answer_quiz)
   end  

    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="intro-header-find" style="margin-top: -50px;">
  <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="shadow">
            <% 2.times do %>
              <%= tag(:br) %>
            <% end %>
            <h1>Atualize seu Perfil</h1>
         </div>
       </div>
     </div>
  </div>
</div>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |city| %>

      <%= city.label :name, "Nome" %>
      <%= city.text_field :name, class: 'form-control' %>

      <%= city.label :email, "Email" %>
      <%= city.email_field :email, class: 'form-control' %>

      <%= city.label :password, "Senha" %>
      <%= city.password_field :password, class: 'form-control' %>

      <%= city.label :password_confirmation, "Confirmação" %>
      <%= city.password_field :password_confirmation, class: 'form-control' %>

      <%= city.submit "Atualizar", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="intro-header-find" style="margin-top: -50px;">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">     
	<div class="shadow">
	  <% 2.times do%>
	    <%= tag(:br) %>
	  <% end %>
	  <h1>Cadastro</h1>
	</div>		
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= flash_message %>
    <%= form_for(@user) do |city| %>
      <%= city.label :name, "Nome" %>
      <%= city.text_field :name, :required => true, class: "form-control" %>

      <%= city.label :email, "Email" %>
      <%= city.email_field :email, :required => true, class: "form-control"%>

      <%= city.label :password, "Password" %>
      <%= city.password_field :password, :required => true, class: "form-control" %>

      <%= city.label :password_confirmation, "Confirmation" %>
      <%= city.password_field :password_confirmation, :required => true, class: "form-control" %>
      <%= tag(:br) %>
      <%= city.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="intro-header-find">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">     
                <div class="shadow">
                    <h1>Perfil</h1>
                </div>      
            </div>
        </div>
    </div>
</div>

<%= @user.name %>, <%= @user.email %>

  <div style="float: left">
    <%= form_tag @user, :id => @user.id, :method => 'get' do |f| %>
  <center>
    <br><br>
    <%if @user.profileQuiz_id == nil%>
        <table class="table">
            <legend>Questionário</legend>
            <tr>
                <td>
                    <font color="red"><%= flash_message %></font>
                </td>
            </tr>
            <tr>
                <td><%= label_tag :uber, 'Você apoia o UBER?' %></td>
                <td><%= radio_button_tag :uber, 1 %>Sim</td>
                <td><%= radio_button_tag :uber, 0 %>Não</td>
            </tr>
        
            <tr>
                <td><%= label_tag :demographic_density, 'Você prefere cidade mais movimentada?'%></td>
                <td><%= radio_button_tag :demographic_density, 0 %>Sim</td>
                <td><%= radio_button_tag :demographic_density, 1 %>Não</td>
            </tr>
            <tr>
                <td><%= label_tag :area, 'Você prefere cidade grande ou pequena?'%></td>
                <td><%= radio_button_tag :area, 0 %>Grande</td>
                <td><%= radio_button_tag :area, 1 %>Pequena</td>
            </tr>
            <tr>
                <td><%= label_tag :population, 'Você prefere cidade mais populosa ou menos populosa?'%></td>
                <td><%= radio_button_tag :population, 0 %>Mais</td>
                <td><%= radio_button_tag :population, 1 %>Menos</td>
            </tr>
            <tr><td></td><td><%= submit_tag "Confirmar" %></td></tr>
            <tr><td><font color="red">*Você poderá responder apenas uma vez.</font></td></tr>
        </table>
    </center>
    <%end%>
    <%end%>
  </div>
  <center>
      <%= link_to "Atualizar Perfil", edit_user_path(current_user), class: "btn btn-primary" %>
      | <%= link_to "Deletar conta", @user, method: :delete,
                                    data: { confirm: "Você tem certeza?" } %>
  </center>