config/routes.rb
Rails.application.routes.draw do

  resources :cities
  
  root 'cities#index'
  get 'auth/:provider/callback', to: "sessions#create_face"
  delete 'sign_out', to: "sessions#destroy_face", as: 'sign_out'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'index' => 'cities#index'
  get 'find' => 'cities#show_cities'
  get 'cities/show'
  get 'show' => 'cities#show'
  get 'compare' => 'cities#compare'
	get 'ranking' => 'cities#ranking'
  post 'compare' => 'cities#compare'
  post 'find' => 'cities#show_cities'
  get 'about' => 'static_pages#about'
  get 'contact' => 'contacts#new', via: 'get'
  get 'references' => 'static_pages#references'
  get "static_pages/download_pdf"
  get "/articles", to: "articles#generate_report", as: :articles
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'edit' => 'users#edit'
  post 'edit' => 'users#update'
  resources :users

  resources :cities do
    resources :comments
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :comments
  validates :name, presence: true
  validates :population, presence: true
  validates :demographic_density, presence: true
  validates :area, presence: true
  validates :fleet, presence: true
  validates :idh, presence: true
  validates :gini, presence: true
  validates :health, presence: true
  validates :violence, presence: true
  validates :image, presence: true
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  include CitiesHelper
  include SessionsHelper
  require 'knn'
  require 'will_paginate/array'

  def index
  end

  def ranking
    @cities = City.all
    order_cities
    @cities = @cities.paginate(:page => params[:page], :per_page => 10)
    if params[:sort_cities]
      attr_to_erb
    end
  end

  def show_cities
    @citiesPaginated = City.paginate(:page => params[:page], :per_page => 12)

    if(params[:find])
      @find = params[:find]
      search_cities
      order_cities
      filter_cities
      @cities = @cities.paginate(:page => params[:page], :per_page => 12)
    else
      @cities = City.all.paginate(:page => params[:page], :per_page => 12)
      @cities = @cities.order(:name)
    end
  end


  def show
    @oldID = params[:id]
    if @oldID != nil
      @city = City.find(@oldID)
    end
    top3
  end

  def compare
    top3
    if(params[:id])
      @oldID = params[:id]
      @city1 = City.find(@oldID)
    end
    if(params[:newID])
      @newID = params[:newID]
      @city2 = City.find(@newID)
      @medals = Hash.new
      @medals = set_medals(@city1, @city2)
    end
    if(params[:find])
      search_cities
      order_cities
    else
      @cities = City.all.sort { |a,b| a.name.downcase <=> b.name.downcase }
    end
    @cities = @cities.paginate(:page => params[:page], :per_page => 12)

  end
end

app/helpers/cities_helper.rb
module CitiesHelper
  def search_cities
    @cities = City.where("name like ?", "%#{params[:find]}%")
  end

  def filter_cities
    if @cities != nil
      @cities.columns.each do |attr|
        if(params[:"from_#{attr.name}"].present?) && (params[:"to_#{attr.name}"].present?)
          @cities = @cities.where("#{attr.name}": params[:"from_#{attr.name}"].to_f .. params[:"to_#{attr.name}"].to_f)
        end
      end
    else
      #do nothing
    end
  end

  def order_cities
    sorted_cities = params[:sort_cities]
    sorted = false
    @cities.columns.each do |attr|
      if(sorted_cities == attribute_to_text[attr.name])
	sorted = true
        if(attr.name == 'demographic_density' || attr.name == 'gini' || attr.name == 'violence' ||
        attr.name == 'fleet')
          @cities = @cities.order(:"#{attr.name}").where("#{attr.name} > ?", 0)
        else
          @cities = @cities.order("#{attr.name}": :desc)
        end
      end
    end

    if(!params[:sort_cities] || !sorted)
      @cities = @cities.order(:name)
    end
  end

  def attr_to_erb
    @attr_name = attribute_to_text.key(params[:sort_cities])
    @attr_rendered = Array.new(1)
    @cities.each do |c|
      aux = ERB.new("<%= c.#{@attr_name} %>").result(binding)
      @attr_rendered.push(aux)
    end
  end

  def top3
    top = Hash.new
    top = {
      'fleet' => City.order(:fleet).first(3),
      'idh' => City.order(idh: :desc).first(3),
      'gini' => City.order(:gini).where("gini > ?", 0).first(3),
      'health' => City.order(health: :desc).first(3),
      'violence' => City.order(:violence).where("violence > ?", 0).first(3)
    }
  end

  def valid_attributes_show_cities
    valid_attributes = Hash.new
    valid_attributes = {
      'population' => true,
      'demographic_density' => true,
      'area' => true,
      'fleet' => true,
      'idh' => true,
      'gini' => true,
      'health' => true,
      'violence' => true
    }
  end

  def valid_attributes_show
    valid_attributes = Hash.new
    valid_attributes = {
      'population' => true,
      'demographic_density' => true,
      'area' => true,
      'fleet' => true,
      'idh' => true,
      'gini' => true,
      'health' => true,
      'violence' => true,
      'uber' => true
    }
  end

  # Attributes that gets better when it gets higher
  def valid_attributes_compare_up
    valid_attributes = Hash.new
    valid_attributes = {
      'population' => true,
      'area' => true,
      'idh' => true,
      'health' => true
    }
  end

  # Attributes that gets worse when it gets higher
  def valid_attributes_compare_down
    valid_attributes = Hash.new
    valid_attributes = {
      'demographic_density' => true,
      'fleet' => true,
      'gini' => true,
      'violence' => true,
    }
  end

  def set_medals (city1, city2)
    medals = Hash.new
    City.columns.each do |attr|
      if(valid_attributes_compare_up[attr.name])
        if(get_average(city1, city2, attr.name) > 50)
          medals[attr.name] = true
        else
          medals[attr.name] = false
        end
      elsif(valid_attributes_compare_down[attr.name])
        if(get_average(city1, city2, attr.name) < 50)
          medals[attr.name] = true
        else
          medals[attr.name] = false
        end
      end
    end
    medals
  end

  def valid_attributes_order
    valid_attributes = Hash.new
    valid_attributes = {
      'population' => 'População Estimada 2015',
      'demographic_density' => 'Densidade Demográfica',
      'area' => 'Tamanho da Cidade',
      'fleet' => 'Transporte',
      'idh' => 'IDH',
      'gini' => 'Índice de Gini',
      'health' => 'Índice de Saúde',
      'violence' => 'Índice de Violência'
    }
  end

  def medal_names
    medal_name = Hash.new
    medal_name = {
      0 => 'gold_medal',
      1 => 'silver_medal',
      2 => 'bronze_medal'
    }
  end

  def attribute_to_text
    attribute_to_text = Hash.new
    attribute_to_text = {
      'name' => 'Nome',
      'population' => 'População Estimada 2015',
      'demographic_density' => 'Densidade Demográfica',
      'area' => 'Tamanho da Cidade',
      'fleet' => 'Transporte',
      'idh' => 'IDH',
      'gini' => 'Índice de Gini',
      'health' => 'Índice de Saúde',
      'violence' => 'Índice de Violência',
      'uber' => 'Uber'
    }
  end

  def attribute_to_description
    attribute_to_description = Hash.new
    attribute_to_description = {
      'population' => "Esse dado indica a quantidade de pessoas que habitavam na cidade no ano de 2015 (Censo mais atual).",
      'demographic_density' => 'Esse dado indica a quantidade de pessoas por quilômetro quadrado na cidade. Indica o quão cheia a cidade está.',
      'area' => 'Esse dado indica o tamanho da cidade em quilômetros quadrados.',
      'fleet' => 'Esse dado indica a quantidade de pessoas por veículos de transporte público,mostrando a cobertura do transporte público dentro da cidade.',
      'idh' => 'Esse dado indica o quão desenvolvida a cidade se encontra. Quanto maior o número, mais desenvolvida ela está.',
      'gini' => 'Esse dado indica o nível de desigualdade existente na cidade. Quanto maior o número, maior a desiguldade.',
      'health' => 'Esse dado indica a cobertura total de estabelecimentos de saúde em relação a quantidade de pessoas e ao tamanho da cidade.',
      'violence' => 'Esse dado mostra a taxa de homícidios por armas de fogo na cidade entre os anos de 2010 e 2012.',
      'uber' => 'Esse dado indica se a cidade possui ou não cobertura do serviço de caronas Uber.'
    }
  end

  def attribute_to_value
    attribute_to_value = Hash.new
    attribute_to_value = {
      'population' => "Habitantes: #{@city.population} Hab",
      'demographic_density' => "Densidade: #{@city.demographic_density} Hab/Km²",
      'area' => "Área: #{@city.area} Km²",
      'fleet' => "Frota: #{@city.fleet} Hab/Onibus",
      'idh' => "IDH: #{@city.idh}",
      'gini' => "Gini: #{@city.gini}",
      'health' => "Saúde: #{@city.health} Hospitais/Densidade",
      'violence' => "Violência: #{@city.violence} homícidios",
      'uber' => "Uber: " + if @city.uber then "Sim" else "Não" end
    }
  end

  def attribute_to_metric
    attribute_to_metric = Hash.new
    attribute_to_metric = {
      'population' => '(Número de habitantes)',
      'demographic_density' => '(Habitantes/Km²)',
      'area' => '(Km²)',
      'fleet' => '(Habitantes/Quantidade de onibus)',
      'health' => '(Densidade/Estabelecimentos de saúde)',
      'violence' => '(Quantidade de homicídios)'
    }
  end

  def get_emoji (attr_name, attr_value)
    emoji = 0
    if attr_name == 'uber'
      emoji = get_emoji_uber(attr_name, attr_value)
    elsif attr_name == 'gini' || attr_name == 'idh'
      emoji = get_emoji_idh_gini(attr_name,attr_value)
    else
      emoji = get_emoji_others(attr_name, attr_value)
    end
    emoji
  end

  def get_emoji_others (attr_name, attr_value)
    emoji = 0
    if valid_attributes_show_cities[attr_name]
      average = City.all.map(&attr_name.to_sym).inject(0, &:+) / City.all.length
      case true
      when (0...average * 0.6).include?(attr_value)
        if attr_name == 'health' then emoji = 1 else emoji = 5 end
      when (average * 0.6...average * 0.9).include?(attr_value)
        if attr_name == 'health' then emoji = 2 else emoji = 4 end
      when (average * 0.9...average * 1.1).include?(attr_value)
        emoji = 3
      when (average * 1.1...average * 1.4).include?(attr_value)
        if attr_name == 'health' then emoji = 4 else emoji = 2 end
      when attr_value > average * 1.4
        if attr_name == 'health' then emoji = 5 else emoji = 1 end
      end
    end
    emoji = set_emojis_by_user(attr_name,emoji)
    
    emoji
  end

  def set_emojis_by_user(attr_name, emoji)
    @current_user = User.find_by(id: session[:user_id])
    if logged_in?
      answers = Hash.new
      answers = get_users_preferences
      if @current_user.profileQuiz_id && !answers[attr_name]
        emoji = 6 - emoji
      else
        #do nothing
      end
    else
      #do nothing
    end
    emoji
  end

  def get_emoji_idh_gini (attr_name, attr_value)
    emoji = 0
    if attr_name == 'gini'
      attr_value = 1 - attr_value
    end
    if attr_value < 0.3
      emoji = 1
    elsif (0.3...0.4).include?(attr_value)
      emoji = 2
    elsif (0.4...0.6).include?(attr_value)
      emoji = 3
    elsif(0.6..0.7).include?(attr_value)
      emoji = 4
    elsif attr_value > 0.7
      emoji = 5
    end
    emoji
  end

  def get_emoji_uber(attr_name, attr_value)
    answers = Hash.new
    if attr_value then emoji = 5 else emoji = 1 end
    emoji = set_emojis_by_user(attr_name, emoji)    
    emoji
  end

  def get_average (city1, city2, attr_name)
    attr_value1 = city1.send(attr_name.to_sym)
    attr_value2 = city2.send(attr_name.to_sym)
    attr_value1 * 100 / (attr_value1 + attr_value2)
  end

  def get_users_preferences
    @profileQuiz = ProfileQuiz.new
    @current_user = User.find_by(id: session[:user_id])
    @profileQuiz.id = @current_user.profileQuiz_id
    @profileQuiz = ProfileQuiz.find_by(id: @profileQuiz.id)
    answers = Hash.new
     
    if @profileQuiz
      @profileQuiz.attributes.each do |attr_name, attr_value|
        if attr_name != 'id'
          answers[attr_name] = attr_value == 1
        else
          #do nothing
        end       
      end
    else
      #do nothing
    end
    answers
  end

  def city_data_array
    data = Array.new
    City.all.each do |city|
      temp = city.attributes.values[2..9]
      if temp[0]
        data[city.id] = city.attributes.values[2..9]
      end
    end
    data
  end

  def suggest_city (city)
    data = city_data_array
    count = data.count
    # data[city.id] = nil
    data = data.compact
    count -= data.count
    knn = KNN.new(data)
    knn = knn.nearest_neighbours(city.attributes.values[2..9] , 13)
    suggest = Array.new
    knn.each do |neighbour|
      if neighbour[0]+count != city.id

app/views/cities/_city_image.html.erb
<td>
	<%= link_to city_path(city), id: "#{city.id}" do %>
		<div class="ih-item circle effect13 from_left_and_right" id=<%= "#{city.id}" %>>
		   	<div class="img"><img src=<%="/assets/#{city.image}.jpg"%> alt="img"></div>
		   	<div class="info">
			    <div class="info-back">
			    <% if city.name.length >= 11 %>
			    	<h3> <font size="3"> <%= city.name %>  </font> </h3>
			    <% else %>
			       	<h3><%= city.name %></h3>
			    <%end%>
			       <p>Estado: <%= city.state%></p>
			    </div>
		   	</div></a>
		</div>
		<h4><%= city.name %></h4>
		<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
	<% end %>
</td>

app/views/cities/_compare1.html.erb
<div style="width: 100%">
 <div style="float: left; width: 50%;">
    <h2><%= @city1.name %></h2>
 </div>
 <div style="float: left; width: 50%;">
    <h2><%= @city2.name %></h2>
 </div>
 <br style="clear: left;" />
</div>
<div class="container">
<center>
    <% @city1.attributes.each do |attr_name, attr_value| %>
        <% if valid_attributes_show_cities[attr_name] %>
            <%= "#{attribute_to_text[attr_name]} #{attribute_to_metric[attr_name]}" %>
                <%if @medals[attr_name] %>
                    <div style="float: left; position: absolute; margin-left: 3%; margin-top: -10px;">
                        <img class=" img-responsive img-rounded" src="/assets/medal.png" style="width: 25px;">
                        </div>
                <%end%>

                <div class="progress" style="width: 80%; position:relative">

                    <div class="progress-bar progress-bar-success progress-bar-striped active" style="width: <%= get_average(@city1, @city2, attr_name)%>%;">
                        <% if(get_average(@city1, @city2, attr_name) > 10) %>
                            <%= attr_value%>
                        <% end %>
                    </div>
                    <div class="progress-bar progress-bar-info progress-bar-striped active" style="width: <%=100- get_average(@city1, @city2, attr_name) %>%">
                        <% if(get_average(@city1, @city2, attr_name) < 90) %>
                            <%= @city2.send(attr_name.to_sym) %>
                        <% end %>
                    </div>
                </div>

                 <%if !@medals[attr_name] %>
                    <div style="position: absolute; margin-left: 82%; margin-top: -50px;float: right;">
                        <img class=" img-responsive img-rounded" src="/assets/medal.png" style="width: 25px;">
                        </div>
                <% end %>
        <% end %>
    <% end %>
</center>

app/views/cities/_compare2.html.erb
<div style="width: 50%;height: 300px;float: left;">
    <center style="margin-top: 300px;">
        <h1><%= @city1.name %></h1>
        <hr class="intro-divider">
    </center>
</div>
<div style="float: right;width: 50%;height: 50%;">
    <h1>Escolha mais uma cidade!</h1><br>
    <ul style="margin-left: 90px; margin-right: 120px;">
        <%= form_tag(compare_path(:id => @oldID)) do %>
            <div class="input-group">
              <%= text_field_tag :find, nil, placeholder: 'Digite o nome da cidade...', size: '10', class: 'form-control' %>
                  <span class="input-group-btn">
                        <%= button_tag(type: "submit", class: "btn btn-primary") do %>
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        <% end %>
                    </span>
            </div>
            <br>
            <div class="input-group">
                <span class="input-group-addon">Ordenar por:</span>
                <%= select_tag :sort_cities, options_for_select(valid_attributes_order.values), prompt: "Ordem alfabética" , class: "form-control"%>
             </div>
        <% end %>
    </ul>
    <br>
    <ul style="margin-left: 90px;">
	<%= will_paginate @cities %>
        <table>
            <% @cities.each_with_index do |city, index| %>
                <% if index%3==0 && index != 0 %>
                    <tr></tr>
                <% end %>
                <td style="width: 100px;">
                    <%= link_to compare_path(:id => @oldID, :newID => city), :class=>'opacityit' , id:"#{city.id}" do %>
                        <img class=" img-responsive img-rounded"src= <%="/assets/#{city.image}.jpg"%> heigth="100" width="100">
                    <% end %>
                    <%=city.name%>
                </td>
                <td>
                <% 11.times do %>
                    &nbsp;
                <% end %>
                </td>
            <% end %>
        </table>
    </ul>   
</div>

app/views/cities/_compare_graph.html.erb
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>

<div id="container" class="container"></div>

<table id="datatable" style="display: none;">
    <thead>
        <tr>
            <th></th>
            <th><%= @city1.name %></th>
            <th><%= @city2.name %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th> êLugar </th>
            <td><%= @city1.population/11967825.0 %></td> <!-- Division by poulation of the most populated city -->
            <td><%= @city2.population/11967825.0 %></td>
        </tr>

        <tr>
            <th> Transporte </th>
            <td><%= top3['fleet'].first.fleet/@city1.fleet %></td>
            <td><%= top3['fleet'].first.fleet/@city2.fleet %></td>
        </tr>
        <tr>
            <th>IDH</th>
            <td><%= @city1.idh %></td>
            <td><%= @city2.idh %></td>
        </tr>
        <tr>
            <th>Gini</th>
            <td><%= @city1.gini %></td>
            <td><%= @city2.gini %></td>
        </tr>
        <tr>
            <th>(Densidade/Estabelecimentos de saúde)</th>
            <td><%= @city1.health/top3['health'].first.health %></td>
            <td><%= @city2.health/top3['health'].first.health %></td>
        </tr>
        <tr>
            <th>(Quantidade de homicídios)</th>
            <td><%= @city1.violence/88.8 %></td> <!-- Division by the index of the most violent city -->
            <td><%= @city2.violence/88.8 %></td>
        </tr>
    </tbody>
</table>


<script>

  $(function () {
    var name1 = [<%= raw @city1.name.to_json %>];
    var name2 = [<%= raw @city2.name.to_json %>];
    $('#container').highcharts({
        data: {
            table: 'datatable'
        },
        chart: {
          backgroundColor: '#E7EDDD',
          type: 'column'
        },
        title: {
            text: 'Grafico de Comparação',
        },

         xAxis: {
            categories: ['População', 'Transporte' ,'IDH', 'Gini', 'Índice de Saúde', 'Índice de Violência']
        },

        yAxis: {
            allowDecimals: true,
            title: {
                text: '@êLugar'
            }
        },
        tooltip: {
            formatter: function () {
                return '<b>' + this.series.name + '</b><br/>';
            }
        }
    });
});
</script>
<br>
<%= link_to "Voltar", compare_path(:id => @oldID), :class => "btn btn-default" %>
<%= link_to "Relatório de Comparação", articles_path(format: :pdf,:city1 => @city1.id, :city2 => @city2.id), target: "_blank", :class => "btn btn-default"%>

app/views/cities/_script_face.html.erb
<script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.6";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

app/views/cities/_suggested_cities.html.erb
<script>
  $("#owl-demo").owlCarousel();
</script>

<div id="owl-demo">

  <% var = suggest_city(@city) %>
   <% var.each_with_index do |city1, index| %>
      <div> <%= render :partial => 'city_image', :locals => { :city => City.find(city1) }  %> </div>
  <% end %>

</div>

app/views/cities/index.html.erb
<body>
  <%#=render 'layouts/navbar'%>
    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <center>
                            <h1><img class=" img-responsive"src="/assets/eLugarLogo.png" heigth="600" width="600"></h1>
                        </center>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons black">
                            <li>
                                <a href="<%= find_path%>" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Ver Cidades</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

	<a  name="services"></a>
    <div class="content-section-a" style="background-color: #E7EDDD;">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Visualize !</h2>
                    <p class="lead">Selecione a cidade que tenha interesse em conhecer e veja informações sobre ela !</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="/assets/visualize.png" alt="">

                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b" style="background-color: #E7EDDD;">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Compare !</h2>
                    <p class="lead"> Faça a comparação entre cidades e veja qual atende mais suas necessidades !</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="/assets/Drawing.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="copyright text-muted small">@eLugar</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/cities/ranking.html.erb
<body>
	<div class="ranking">
		<%= form_tag(ranking_path, :method => :get) do %>
			<div class="input-group">
				<span class="input-group-addon">Ordenar por:</span>
				<%= select_tag :sort_cities, options_for_select(valid_attributes_order.values), class: "form-control" %>
				<span class="input-group-btn">
				<%= button_tag(type: "submit", class: "btn btn-primary",id:"view_ranking") do %>
					Visualizar
				<% end %>
				</span>
			<% end %>
		</div>
	</div>
		<% if params[:sort_cities]%>
			<div class = "rank-table">
			<table class = "table table-striped table-hover table-bordered">
				<tr class = "active">
					<td>#</td> <td>Nome:</td> <td><%= params[:sort_cities] %></td>
				</tr>
				<% @cities.each_with_index do |city, index| %>
					<tr>
						<td><%= (@cities.current_page-1)*10 + index + 1 %></td>
						<td><%= link_to city_path(city) do %>
							<%= city.name %>
						<% end %></td>
						<td><%= @attr_rendered.at(index+1) %></td>
					</tr>
				<% end %>
				<center>
					<%= will_paginate @cities %>
				</center>
		<% end %>
	</div>
</body>

app/views/cities/show.html.erb
  <div id="fb-root"></div>
  <%=render 'cities/script_face'%>
    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header-show">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message-show black">
                        <h2>Análise da Cidade</h2>
                        <hr class="intro-divider">
                        <div class="list-inline intro-social-buttons black">
                            <ul class="cardboard">
                                <%= form_tag(cities_show_path, :method => :get) do %>
                                    <h1>  <%= @city.name %> </h1>
                                    <%= render 'cardboard' %>
                                <% end %>
                            </ul>
                        </div>
                        <div>
                         <%= link_to "Voltar", find_path(:id => nil), :class => "btn btn-default" %>&nbsp;&nbsp;
                         <%= link_to "Compare", compare_path(:id => @oldID), :class => "btn btn-primary" %>
                           <%= form_tag(cities_show_path, :method => :get) do %>
                             <center>
                                <br><br><br><div class="fb-like" data-href ="/cities/<%=@city.id%>" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
                             </center>
                           <%end%>
                       </div>
                       <h2>Veja também:</h2>
                       <%= render 'suggested_cities' %>
                       <% 2.times do %>
         		             <%= tag(:br) %>
                       <% end %>
                        <h2>Comentários</h2>
                        <% @city.comments.each_slice(2) do |f| %>
                            <%= render f[0]%>
                        <% end %>
                        <% if current_user%>
                        <h2>Adicionar um comentário:</h2>
                        <%= render 'comments/form' %>

                        <% end %>
                        <%= link_to 'Top', city_path %>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container -->
    </div>
</body>

app/views/cities/show_cities.html.erb
<body>
    <!-- Header -->
    <div class="intro-header-find">
    <div class="container">
        <div class="row">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message-find">
                        <div class="shadow">
                            <h1>Escolha a cidade que deseja conhecer !</h1>
                        </div>
                        <hr>
                        <ul class="list-inline intro-social-buttons black">
                            <li>
                                <%= form_tag(find_path, :method => :get) do %>
                                    <div class="input-group">
                                        <%= text_field_tag :find, nil, placeholder: 'Digite o nome da cidade...', size: '50', class: 'form-control' %>
                                        <span class="input-group-btn">
                                            <%= button_tag(type: "submit", class: "btn btn-primary") do %>
                                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                        </span>
                                    <% end %>
                                    </div>
                                    <br>
                                    <%= render 'order_and_filter' %>
                                <% end %>
                            </li>
                            <li>
                                <table>
                                    <% @cities.each_with_index do |city, index| %>
                                        <% if index%3==0 && index != 0 %>
                                            <tr>
                                        <% end %>
                                        <%= render :partial => 'city_image', :locals => { :city => city} %>
                                    <% end %>
                                    <% if @find %>
                                        <%= will_paginate @citiesPaginated, :params => {:find => @find} %>
                                    <% else %>
                                        <%= will_paginate @citiesPaginated %>
                                    <% end %>
                                </table>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>