config/routes.rb
Rails.application.routes.draw do

  resources :cities
  
  root 'cities#index'
  get 'auth/:provider/callback', to: "sessions#create_face"
  delete 'sign_out', to: "sessions#destroy_face", as: 'sign_out'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'index' => 'cities#index'
  get 'find' => 'cities#show_cities'
  get 'cities/show'
  get 'show' => 'cities#show'
  get 'compare' => 'cities#compare'
	get 'ranking' => 'cities#ranking'
  post 'compare' => 'cities#compare'
  post 'find' => 'cities#show_cities'
  get 'about' => 'static_pages#about'
  get 'contact' => 'contacts#new', via: 'get'
  get 'references' => 'static_pages#references'
  get "static_pages/download_pdf"
  get "/articles", to: "articles#generate_report", as: :articles
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'edit' => 'users#edit'
  post 'edit' => 'users#update'
  resources :users

  resources :cities do
    resources :comments
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

end

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="sortcut icon" href="assets/eLugarLogo.ico" type="image/x-icon" />
    <title>êLugar</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../assets/stylesheets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../../assets/stylesheets/landing-page.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
  <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
      <div class="container topnav">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="inavbacon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="/"><img src="../assets/eLugarLogo.ico" class="logo" ></a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse white" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <% if logged_in? %>
                      <li>
                          <%= link_to "Perfil", current_user %>
                      </li>
                      <li>
                          <%= link_to "Log out", logout_path, method: "delete" %>
                      </li>
                  <% else %>
                      <li>
                          <%= link_to "Cadastro", signup_path %>
                      </li>
                      <li>
                          <%= link_to "Login", login_path %>
                      </li>
                  <% end %>
                  <li>
                      <%= link_to "Ranking", ranking_path %>
                  </li>
                  <li>
                      <%= link_to "Sobre", about_path %>
                  </li>
                  <li>
                      <%= link_to "Referências", references_path %>
                  </li>
                  <li>
                      <%= link_to "Contato", contact_path %>
                  </li>
              </ul>
          </div>
            <!-- /.navbar-collapse -->
      </div>
        <!-- /.container -->
  </nav>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>êLugar</title>

  <%= javascript_include_tag "/assets/bootstrap.min.js"%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/navbar' %>
<%= yield %>
</body>
</html>